services:
  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/users_db
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongodb
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:3002"
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_DIALECT: mysql
      NODE_ENV: ${NODE_ENV}
      KAFKA_BROKERS: kafka:9092
    depends_on:
      mysql_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  cart-service:
    build: ./cart-service
    ports:
      - "${CART_SERVICE_PORT}:3003"
    environment:
      PG_HOST: postgresql_db
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_DIALECT: postgres
      REDIS_HOST: redis_cache
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: ${NODE_ENV}
      KAFKA_BROKERS: kafka:9092
    depends_on:
      postgresql_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./cart-service:/app
      - /app/node_modules

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql_db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: "confluentinc/cp-zookeeper:7.5.0"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network
    healthcheck:
      # Use the Confluent-provided tool to check if Zookeeper is ready
      test: ["CMD-SHELL", "cub zk-ready zookeeper:2181 30"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: "confluentinc/cp-kafka:7.5.0"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      # Use the Confluent-provided tool to check if Kafka is ready
      test: ["CMD-SHELL", "cub kafka-ready -b kafka:9092 1 30"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
  mysql_data:
  postgresql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
