version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/users_db
      JWT_SECRET: RIZON_Rahi
      JWT_EXPIRES_IN: 1h
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - ./user-service:/app
      - /app/node_modules

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: "Rizon11#"
      DB_NAME: products_db
      DB_DIALECT: mysql
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - ./product-service:/app
      - /app/node_modules

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
