services:
  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/users_db
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - mongodb
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:3002"
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_DIALECT: mysql
      NODE_ENV: ${NODE_ENV}
    depends_on:
      mysql_db:
        condition: service_healthy # Wait for the healthcheck to pass
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  mysql_data:

networks:
  app-network:
    driver: bridge
